import "@/app/global.css";

import { NextIntlClientProvider, useLocale } from "next-intl";
import { notFound } from "next/navigation";
import Header from "@components/Global/Header";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  // @ts-ignore
  children,
  // @ts-ignore
  params,
}) {
  const locale = useLocale();

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  const messages = (await import(`../../../messages/${locale}.json`)).default;

  return (
    <>
      <Header />
      <section className="py-6 sm:py-8 lg:py-12">
        <div className="mx-auto max-w-screen-2xl px-4 md:px-8">
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
        </div>
      </section>
    </>
  );
}
